sudo: required
language: java
jdk:
- openjdk8
services:
  - docker

before_install:
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
- chmod +x gradlew
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

branches:
  only:
  - master

sudo: false
dist: trusty
addons:
  sonarcloud:
    organization: "allanmleite-github"
  token:
    secure: 67fcef9a42fc64f54051404ac52232a24dca2c73

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script:
- ./gradlew sonarqube -Dsonar.projectKey=AllanMLeite_scd-demo -Dsonar.organization=allanmleite-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=67fcef9a42fc64f54051404ac52232a24dca2c73
- docker build -t allanmleite/scd-demo .
- docker tag allanmleite/scd-demo registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: script
  script:
    docker push allanmleite/scd-demo;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  branch: master
