language: java
jdk:
- openjdk8

before_install:
- chmod +x gradlew

branches:
  only:
  - master

sudo: false
dist: trusty
addons:
  sonarcloud:
    organization: "allanmleite-github"
  token:
    secure: 67fcef9a42fc64f54051404ac52232a24dca2c73

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: ./gradlew sonarqube -Dsonar.projectKey=AllanMLeite_scd-demo -Dsonar.organization=allanmleite-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=67fcef9a42fc64f54051404ac52232a24dca2c73

after_success:
  - deploy:
      provider: heroku
      api_key:
        secure: 6c7d38bf-b556-436d-95e1-032327014f64
